#!/usr/bin/env bash

echo Konwersja mp4
echo Wprowadz nazwe pliku bez rozszerzenia
read name
var1="$name"
mp=".mp4"
out=".out.mp4"
par1="$var1$mp"
par2="$var1$out"

time ffmpeg -i $par1 -filter_complex '[0:v]scale=ih*16/9:-1,boxblur=luma_radius=min(h\,w)/20:luma_power=1:chroma_radius=min(cw\,ch)/20:chroma_power=1[bg];[bg][0:v]overlay=(W-w)/2:(H-h)/2,crop=h=iw*9/16' $par2
echo Ukonczono, $par2
