#!/usr/bin/env bash

echo Przesuwanie audio
echo Wprowadz nazwe pliku bez rozszerzenia
read name
var1="$name"
mp=".mp4"
out=".mkv"
par1="$var1$mp"
par2="$var1$out"

time ffmpeg -i "$par1" -itsoffset -0.40 -i "$par1" -map 1:v -map 0:a -c:a aac -c:v copy "$par2"
echo Ukonczono, $par2
