#!/usr/bin/env bash

echo Konwersja mp4
echo Wprowadz nazwe pliku bez rozszerzenia
read name
var1="$name"
mp=".mp4"
out=".out.mp4"
par1="$var1$mp"
par2="$var1$out"

time ffmpeg -i $par1 -c:v copy -c:a ac3 $par2
echo Ukonczono, $par2
